-- AlterTable
ALTER TABLE "characters" ALTER COLUMN "min_x" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "max_x" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "min_y" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "max_y" SET DATA TYPE DOUBLE PRECISION;
